### ISSUE TITLE
安装完依赖 提示localStorage is not defined

### ISSUE THREAD

**Issue by songjingyang** [minaxorg/countdown#1]
ReferenceError: localStorage is not defined

**Comment by hellohejinyu** [comment]
两种情况，一是你的 React 不是用于开发 Web 页面，全局环境下没有 localStorage 对象，刚刚发布了新版本支持自定义 getter 和 setter 方法，可以解决这个问题。

另一种情况是你使用了服务端渲染，这个暂不支持。
